<?php

namespace Zitec\EmagMarketplace\Setup\Traits;

use Magento\Catalog\Model\Product;
use Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface;
use Magento\Eav\Setup\EavSetup;
use Zitec\EmagMarketplace\Model\ProductAttributes;

/**
 * Trait ProductDataTrait
 * @package Zitec\EmagMarketplace\Setup\Traits
 */
trait ProductDataTrait
{
    protected $attributes = [
        ProductAttributes::IS_VISIBLE => [
            'type' => 'int',
            'backend' => '',
            'frontend' => '',
            'label' => 'Visible to eMag Marketplace',
            'input' => 'boolean',
            'class' => '',
            'source' => '',
            'group' => 'eMag Marketplace',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => 0,
            'searchable' => false,
            'filterable' => true,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => true,
            'unique' => false,
            'apply_to' => 'simple'
        ],
        ProductAttributes::PART_NUMBER_KEY => [
            'type' => 'varchar',
            'backend' => '',
            'frontend' => '',
            'label' => 'Part Number Key',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'group' => 'eMag Marketplace',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::BRAND => [
            'type' => 'varchar',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Brand',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::EAN => [
            'group' => 'eMag Marketplace',
            'type' => 'varchar',
            'backend' => '',
            'frontend' => '',
            'label' => 'EAN',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::WARRANTY => [
            'type' => 'int',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Warranty',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::IS_SENT => [
            'type' => 'int',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Is sent to eMag',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => false,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::SENT_DATA => [
            'type' => 'text',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Data sent to eMag (complete)',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => false,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
        ],
        ProductAttributes::STATUS => [
            'type' => 'text',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Emag Status',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => true,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
            'is_used_in_grid' => true,
        ],
        ProductAttributes::VALIDATION_STATUS => [
            'type' => 'text',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Validation Status',
            'input' => 'textarea',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => true,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
            'is_used_in_grid' => true,
        ],
        ProductAttributes::OFFER_VALIDATION_STATUS => [
            'type' => 'text',
            'group' => 'eMag Marketplace',
            'backend' => '',
            'frontend' => '',
            'label' => 'Offer Validation Status',
            'input' => 'textarea',
            'class' => '',
            'source' => '',
            'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => false,
            'filterable' => true,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => false,
            'unique' => false,
            'apply_to' => 'simple',
            'is_used_in_grid' => true,
        ],
    ];

    /**
     * @param EavSetup $productSetup
     */
    public function createProductAttributes(EavSetup $productSetup)
    {
        foreach ($this->attributes as $name => $attribute) {
            $productSetup->removeAttribute(Product::ENTITY, $name);
            $productSetup->addAttribute(Product::ENTITY, $name, $attribute);
        }
    }
}
