<?php /** @var \Zitec\EmagMarketplace\Block\Adminhtml\Mapping\Edit\Category\Category $block */ ?>

<input type="hidden" class="js-emkp-mapping-input" name="id" value="<?= $this->getMappingId(); ?>">

<div class="admin__field _required emkp-admin__field" data-index="emag_category_id">
    <label class="admin__field-label emkp-admin__field-label" for="emag_category_id">
        <span><?= __('Emag Category:') ?></span>
    </label>
    <div class="admin__field-control emkp-admin__field-control">
        <select class="admin__control-select js-emkp-mapping-input" name="emag_category_id" id="emag_category_id"
                aria-describedby="notice-emag_category_id" required>
            <option data-title="<?= __('Select category'); ?>" value="0" disabled
                    <?php if (!$this->getEmagCategoryId()){ ?>selected<?php } ?>>
                <?= __('Select category'); ?>
            </option>

            <?php foreach ($this->getEmagCategories() as $emagCategory) { ?>
                <option data-title="<?= $emagCategory->getName(); ?>" value="<?= $emagCategory->getId(); ?>"
                        <?php if ($this->getEmagCategoryId() == $emagCategory->getId()){ ?>selected<?php } ?>
                >
                    <?= $emagCategory->getName(); ?>
                </option>
            <?php } ?>
        </select>
    </div>
</div>

<div class="admin__field _required emkp-admin__field" data-index="magento_category_id">
    <label class="admin__field-label emkp-admin__field-label" for="magento_category_id">
        <span><?= __('Magento Category:') ?></span>
    </label>
    <div class="admin__field-control emkp-admin__field-control">
        <select class="admin__control-select js-emkp-mapping-input" name="magento_category_id" id="magento_category_id"
                aria-describedby="notice-magento_category_id" required>
            <option data-title="<?= __('Select category'); ?>" value="0" disabled
                    <?php if (!$this->getMagentoCategoryId()){ ?>selected<?php } ?>>
                <?= __('Select category'); ?>
            </option>
            <?php foreach ($this->getMagentoCategories() as $magentoCategory) { ?>
                <option data-title="<?= $magentoCategory['label']; ?>" value="<?= $magentoCategory['value']; ?>"
                    <?php if ($magentoCategory['disabled'] && $this->getMagentoCategoryId() != $magentoCategory['value']) { ?> disabled<?php } ?>
                        <?php if ($this->getMagentoCategoryId() == $magentoCategory['value']){ ?>selected<?php } ?>
                >
                    <?= $magentoCategory['label']; ?>
                </option>
            <?php } ?>
        </select>

        <label class="admin__field-error js-emkp-mapping-error">
            This is a required
            field.
        </label>
    </div>
</div>

